"""club event hub

Revision ID: ddcf224a1d10
Revises: 20260921_0004
Create Date: 2026-09-22 00:13:16.335920
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ddcf224a1d10"
down_revision: str | None = "20260921_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("tagline", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("activities", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clubs")),
    )
    op.create_table(
        "club_admins",
        sa.Column("club_id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "appointed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_club_admins_club_id_clubs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_club_admins_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("club_id", "user_id", name=op.f("pk_club_admins")),
    )
    op.create_table(
        "club_creation_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("tagline", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("activities", sa.JSON(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("approved_club_id", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected')",
            name=op.f("ck_club_creation_requests_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_club_id"],
            ["clubs.id"],
            name=op.f("fk_club_creation_requests_approved_club_id_clubs"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_club_creation_requests_requester_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_club_creation_requests_reviewer_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_creation_requests")),
        sa.UniqueConstraint(
            "approved_club_id", name=op.f("uq_club_creation_requests_approved_club_id")
        ),
    )
    op.create_index(
        op.f("ix_club_creation_requests_requester_id"),
        "club_creation_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_table(
        "club_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("club_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=250), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "registration_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("registration_closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_paid", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("fee", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bkash_number", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_paid = false) OR (registration_enabled = true "
            "AND fee > 0 AND bkash_number IS NOT NULL)",
            name=op.f("ck_club_events_valid_paid_setup"),
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_club_events_valid_time_range")
        ),
        sa.CheckConstraint("fee >= 0", name=op.f("ck_club_events_valid_fee")),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_club_events_club_id_clubs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_events")),
    )
    op.create_index(
        op.f("ix_club_events_club_id"), "club_events", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_club_events_ends_at"), "club_events", ["ends_at"], unique=False
    )
    op.create_index(
        op.f("ix_club_events_starts_at"), "club_events", ["starts_at"], unique=False
    )
    op.create_table(
        "club_members",
        sa.Column("club_id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_club_members_club_id_clubs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_club_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("club_id", "user_id", name=op.f("pk_club_members")),
    )
    op.create_table(
        "event_interests",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "status IN ('interested','going')",
            name=op.f("ck_event_interests_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["club_events.id"],
            name=op.f("fk_event_interests_event_id_club_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_interests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "user_id", name=op.f("pk_event_interests")),
    )
    op.create_table(
        "event_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('started','finished')",
            name=op.f("ck_event_notifications_valid_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["club_events.id"],
            name=op.f("fk_event_notifications_event_id_club_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_notifications")),
        sa.UniqueConstraint(
            "event_id", "user_id", "kind", name="uq_event_notification_state"
        ),
    )
    op.create_index(
        op.f("ix_event_notifications_user_id"),
        "event_notifications",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "event_registrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("participant_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("student_id", sa.String(length=64), nullable=False),
        sa.Column("department_name", sa.String(length=100), nullable=False),
        sa.Column("bkash_trx_id", sa.String(length=100), nullable=True),
        sa.Column("payment_status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "payment_status IN ('not_required','pending_review','verified','rejected')",
            name=op.f("ck_event_registrations_valid_payment_status"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["club_events.id"],
            name=op.f("fk_event_registrations_event_id_club_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_registrations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_registrations")),
        sa.UniqueConstraint("event_id", "user_id", name="uq_event_registration_user"),
    )
    op.create_index(
        op.f("ix_event_registrations_event_id"),
        "event_registrations",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_event_registrations_event_id"), table_name="event_registrations"
    )
    op.drop_table("event_registrations")
    op.drop_index(
        op.f("ix_event_notifications_user_id"), table_name="event_notifications"
    )
    op.drop_table("event_notifications")
    op.drop_table("event_interests")
    op.drop_table("club_members")
    op.drop_index(op.f("ix_club_events_starts_at"), table_name="club_events")
    op.drop_index(op.f("ix_club_events_ends_at"), table_name="club_events")
    op.drop_index(op.f("ix_club_events_club_id"), table_name="club_events")
    op.drop_table("club_events")
    op.drop_index(
        op.f("ix_club_creation_requests_requester_id"),
        table_name="club_creation_requests",
    )
    op.drop_table("club_creation_requests")
    op.drop_table("club_admins")
    op.drop_table("clubs")
    # ### end Alembic commands ###
